### ISSUE TITLE
Pengantar RESTful

### ISSUE THREAD

**Issue by nauticas** [nauticas/RESTful#2]
deskripsi tentang RESTful

**Comment by d8920ya** [comment]
Sudah ditambahkan penjelasan singkat mengenai arsitektur REST dan sudah dibuat [Pull Request](https://github.com/nauticas/RESTful/pull/5) . Mohon dicek dan dilakukan `merge` apabila penjelasan sudah dirasa sesuai. Terima kasih .

**Comment by nauticas** [comment]
sudah sesuai mas isue saya close ya
